# mypy: disable-error-code="import-untyped"
from typing import Callable, Dict, List, Optional

from ipywidgets.widgets.trait_types import InstanceDict
from ipywidgets.widgets.widget_box import Box
from ipywidgets.widgets.widget_string import HTMLStyle, _String
from traitlets.traitlets import HasTraits

class Widget:
    """Base class for all Jupyter widgets."""

    keys: List[str]
    comm: object

    def __init__(self, **kwargs: object) -> None: ...
    def observe(self, handler: Callable[..., object], names: object = ..., type: str = ...) -> None: ...
    def unobserve(self, handler: Callable[..., object], names: object = ..., type: str = ...) -> None: ...
    def unobserve_all(self, name: object = ...) -> None: ...
    def on_msg(self, callback: Callable[..., object], remove: bool = False) -> None: ...
    def send(self, content: Dict[str, object], buffers: Optional[List[object]] = None) -> None: ...
    def add_traits(self, **traits: object) -> None: ...
    def has_trait(self, name: str) -> bool: ...
    def set_trait(self, name: str, value: object) -> None: ...
    def close(self) -> None: ...

class DOMWidget(Widget):
    """Base class for all Jupyter widgets that have a DOM view."""

    layout: object
    tooltip: Optional[str]

    def __init__(self, **kwargs: object) -> None: ...
    def add_class(self, className: str) -> 'DOMWidget': ...
    def remove_class(self, className: str) -> 'DOMWidget': ...
    def blur(self) -> None: ...
    def focus(self) -> None: ...

class Output(DOMWidget):
    def __enter__(self) -> None: ...
    def __exit__(self, etype: object, evalue: object, tb: object) -> None: ...

class LoggingHasTraits(HasTraits): ...
class CallbackDispatcher(LoggingHasTraits): ...

class HTML(_String):  # type: ignore
    style = InstanceDict(HTMLStyle)

class VBox(Box):  # type: ignore
    pass
