[tox]
envlist = py312, coverage-report, junit-report, lint, # type-check
basepython = python3.12
skip_missing_interpreters = false

[pytest]
# Only look for tests in the "tests" folder
testpaths =
    src
    tests
addopts =
    --doctest-modules
    --ignore=src/netlist_carpentry/io/read/yosys_netlist_types.py
    --ignore=src/netlist_carpentry/io/read/yosys_netlist.py

[testenv]
passenv = *
runner = uv-venv-lock-runner
commands = pytest --ignore=oss-cad-suite --cov netlist_carpentry --cov-append --cov-report= --junitxml=reports/junit-{envname}.xml --junit-prefix={envname}
extras = vcd

[testenv:coverage-report]
runner = uv-venv-runner
depends =
    py312
skip_install = true
ignore_errors = true
deps = coverage[toml]
commands =
    coverage report
    coverage xml
    coverage html --title="Code Coverage for netlist_carpentry"
    coverage erase

[testenv:junit-report]
runner = uv-venv-runner
depends =
    py312
    # type-check
skip_install = true
deps = junitparser
commands =
    junitparser merge --glob reports/junit-*.xml reports/junit.xml

# [testenv:type-check]
# ignore_errors = true
# commands =
#     mypy -p netlist_carpentry --junit-xml reports/junit-type-check.xml

[testenv:lint]
ignore_errors = true
deps =
    ruff==0.14.* # Pinned to specific version, since it somehow broke in one of the repos during one run
commands =
    ruff check src/netlist_carpentry
    ruff check tests
